# Generated by Django 2.1 on 2019-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190321_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user4',
            field=models.TextField(blank=True),
        ),
    ]
