# Generated by Django 2.1 on 2019-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_post_user4'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client',
            field=models.TextField(blank=True),
        ),
    ]
