# Generated by Django 2.1 on 2019-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_post_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.TextField(blank=True),
        ),
    ]
