# Generated by Django 2.2 on 2019-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190601_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='General_Features',
        ),
    ]
